services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 'MvKraftCluster-1234567890abcdef'
    volumes:
      - kafka_data:/var/lib/kafka/data
    command:
      - /bin/bash
      - -c
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "Formatting storage (KRaft)..."
          /opt/kafka/bin/kafka-storage.sh format -t MvKraftCluster-1234567890abcdef -c /opt/kafka/config/kraft/server.properties
        fi
        echo "Starting Kafka in KRaft mode..."
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties

  redis-master:
    image: redis:7
    container_name: redis-master
    volumes:
      - ./redis/redis-master.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      redisnet:
        aliases:
          - redis-master

  redis-slave-1:
    image: redis:7
    container_name: redis-slave-1
    depends_on:
      - redis-master
    volumes:
      - ./redis/redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
    networks:
      - redisnet

  sentinel-1:
    image: redis:7
    container_name: sentinel-1
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/:/usr/local/etc/redis/
    command: ["redis-server", "/usr/local/etc/redis/sentinel-26379.conf", "--sentinel"]
    ports:
      - "26379:26379"
    networks:
      - redisnet

  sentinel-2:
    image: redis:7
    container_name: sentinel-2
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/:/usr/local/etc/redis/
    command: ["redis-server", "/usr/local/etc/redis/sentinel-26380.conf", "--sentinel"]
    ports:
      - "26380:26379"
    networks:
      - redisnet

  sentinel-3:
    image: redis:7
    container_name: sentinel-3
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/:/usr/local/etc/redis/
    command: ["redis-server", "/usr/local/etc/redis/sentinel-26381.conf", "--sentinel"]
    ports:
      - "26381:26379"
    networks:
      - redisnet

volumes:
  kafka_data:

networks:
  redisnet:
    external: true